### ISSUE TITLE
On https://openshift.io, seeing tokens refreshed.....constantly

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1049]
See screenshot of console log:

![screenshot from 2017-04-25 08-48-45](https://cloud.githubusercontent.com/assets/642621/25386088/20035932-2994-11e7-9fdf-0b556c4a3c52.png)

**Comment by alexeykazakov** [comment]
We switched to 30 day tokens in our Keycloak instead of 1 day token last night.
And this morning a few people noticed that UI refreshing tokens constantly.
I switched to 1 day token to see if it solves the problem and that constant refresh stopped.
Then I switched it back to 30 days but we don't see that refresh problem since then.

**Comment by ldimaggi** [comment]
It's back...

![screenshot from 2017-04-25 18-52-14](https://cloud.githubusercontent.com/assets/642621/25411056/6f66edd2-29e8-11e7-874b-8dbee1928b67.png)

**Comment by alexeykazakov** [comment]
https://goo.gl/YOzwja

**Comment by alexeykazakov** [comment]
It's reproducible only on the front page.
I login then remove /_home and see in the console:
`Refreshing token in: 14000 milliseconds.`
Then in 14 seconds it starts constantly refreshing the token.
If I go somewhere else, to profile for example, it stops.

**Comment by joshuawilson** [comment]
@pmuir it looks like this error only happens in the landing page. Can you please take a look at it.

**Comment by alexeykazakov** [comment]
setTimeout() uses a 32 bit int to store the delay. So the max value allowed is 2147483647
But since we switched to 30 day tokens the token expiry now is bigger than that int which causes immediate refreshing.
Actually we need to refresh in 10 minutes or in 90% of the expiry time whatever is sooner so that will fix the problem.
