### ISSUE TITLE
lets add a real real time status UI that shows the status and version of the tenant services

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#1470]
here's a screenshot of my current prototype - PR on its way shortly
<img width="314" alt="fabric8" src="https://user-images.githubusercontent.com/30140/26896220-e8cacf8c-4bbb-11e7-8850-749afebe3ab4.png">

**Comment by joshuawilson** [comment]
@jstrachan currently @pmuir is working on the Status, maybe he can add this to it.

**Comment by pmuir** [comment]
My status API is more for the shared services rather than the tenant services.

Shouldn't the version numbers go the About dialog?

**Comment by jstrachan** [comment]
Maybe we can combine efforts then (phew glad we were not reimplementing the same thing ;). 

I put the version in there too as finding the version and the status require the same kinda thing (finding the pod/deployment) for tenant stuff; but happy to hide the version and add to the about if you prefer. Should be easy to refactor the controller that groks the tenant status information into a service we can share in both UIs

**Comment by jstrachan** [comment]
The tenant service stuff is actually much much harder; e.g. finding out the tenant namespace/entity isn't possible from the router on the home page for example :)

**Comment by pmuir** [comment]
Yep - add it to about.

Agreed on the controller, mine is super simple on the UI side, so just PR yours and I can fit around it.

**Comment by pmuir** [comment]
Yes, tenant status stuff is the hard bit. SG has some tenant info on his status API but need to talk to him to find out more.

**Comment by jstrachan** [comment]
here's the PR which hopefully gets built soon with my minor PR for fabric8-ui to use this new widget
https://github.com/fabric8-ui/fabric8-runtime-console/pull/501

**Comment by rawlingsj** [comment]
from the snapshot build deployed at https://fabric8-ui-fabric8-ui-pr-501-fabric8-runtime-console.int.rdu2c.fabric8.io - the status works great!

I wonder if there's a middle ground to the discussion above, rather than having 
foo : version 1.2.3
we had
foo : 1.2.3
i.e. omitting the word 'version' so it looks cleaner but keeps the quick indication of what version is running?  

Also while users seem to have to click the button to upgrade tenant apps and until we figure out a decent notification or auto update strategy..  I wonder if we should visualise in the status that a new version is available in a nice way?  So folks either have a quick click button on the status menu or at least know to go to the update profile?  It's another PR but figured it was worth mentioning whilst I thought of it.

<img width="407" alt="screenshot 2017-06-07 23 36 19" src="https://user-images.githubusercontent.com/1457180/26904523-3968e154-4bda-11e7-89ef-da53f1a901be.png">

**Comment by joshuawilson** [comment]
I like that idea @rawlingsj

**Comment by jstrachan** [comment]
I like it; I did wonder if we detect there's a new version we should show the `Update Tenant` button too. 
Though I guess ultimately we'll be automatically upgrading tenants for the user; so it'll just happen in the background anyways?

**Comment by jstrachan** [comment]
@rawlingsj the next PR build will have the `version` text removed and a tool top added in case folks wonder what the number is ;)

**Comment by rawlingsj** [comment]
I like it!

![status-img](https://user-images.githubusercontent.com/1457180/26921975-94b805e8-4c35-11e7-90de-e460413c48f1.png)

**Comment by sbose78** [comment]
This looks awesome @jstrachan !
Would there be a way to convey that we are using "Jenkins 2" with 'our distribution' version of '3.0.31' ?

**Comment by jstrachan** [comment]
we only use jenkins 2 ;) so I guess that could go on the About page?
