### ISSUE TITLE
What does the logged out menu look like?

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#25]
Define what the nav system looks like when the user is not logged in e.g. they are sent a link.

The right hand dropdown clearly needs updating (e.g. a sign in link), but of greater interest is the main nav structure, where a number of menus no longer make sense (e.g. settings).

This needs some thought, so for now let's assume that all pages require a user to be logged in.

**Comment by pmuir** [comment]
/cc @qodfathr

@joshuawilson I rewrote the description as it's actually more about the main nav structure.

**Comment by qodfathr** [comment]
The nav system basically looks the same, although the 'Profile' icon (your pix) in the upper right is replaced with a Sign In button, and the "Context" drop-down in the upper left is probably removed.

What's more important is that some screens will not render if you are not logged in -- they can just redirect you to home for now. We need a way to indicate which screens have this  behavior.

And, in a semi-related way, the user profile page (e.g. fabric8.io/userid) should only display **all** of the data if the user is the one viewing it. If another user is viewing that page (e.g. I am viewing Pete's profile page), then the visibility of some of the data should be controlled by the permissions Pete has offered (e.g. show full name, show email address, etc.). More importantly, this has to happen within the APIs itself -- you cannot solve this in the front-end Javascript, because that would be a security hole (e.g. if not limited by the API, then I could write my own web page and reveal your email address to the world, even if you did not want that to happen.)

**Comment by joshuawilson** [comment]
@qodfathr I completely agree with the need to constrain what data the user can view is controlled by the back end by the backend.

As for the pages. We can hide pages or even tabs or just parts of pages. If you mark it up, we can control what is viewed while logged out.

We already applied this logic to the Planner. You have to be logged in to edit anything but if you aren't logged in then you can see the data but not change it. We have the constraint in the UI to make the experience better but the real constraint is in the back-end.

**Comment by jstrachan** [comment]
when you logout I'd assume you're redirected to the OAuth login page; so there's no nav structure when you're not logged in?

**Comment by qodfathr** [comment]
@jstrachan you should not need to be logged in to navigate/read content which is open to anonymous browsing (which, for v1, is almost everything). e.g., if I'm not logged into GitHub I can still visit https://github.com/fabric8io/fabric8, use the navigation, etc. In fact, some operations are still visible -- e.g., create a fork -- but any attempt to use them prompts me to log in. Upon doing so, I'm still in the context of the initiating operation and can complete it.

Some of the nav structure may be a little different when not logged in, but, for the most part, it's the same as when logged in.

When we start talking about private Spaces, things will be different. The owner of a private Space will be able to make it anonymously browsable. (Most?) others will lock it down to only authorized viewing. When an unauthorized user attempts to access such content, we still need to determine what the behavior should be. GitHub shows a 404, which I'm not sure feels right. Technically, 403 would be more correct, but, on the other hand, returning a 403 actually leaks information. (e.g., if I navigate to /SomeSpace/foo and get a 403, then I know that 'foo' exists). That's why I think GitHub returns a 404. We could choose to do a redirect to home, signin, etc., but somehow each one of those feels awkward to me.

**Comment by jstrachan** [comment]
@qodfathr guess it depends what resources we're talking about. 

Public OSS projects source + issues are visible by anyone on github. But when it comes to a user or teams environments, builds & apps on, say, OpenShift Online I figured there'd be nothing to browse until you login to your OpenShift Online cluster.

What stuff is gonna be public? e.g. right now I'm not sure there's any concept of public browsable resources in OpenShift; the assumption is you login and then each user gets to see certain resources

**Comment by qodfathr** [comment]
@jstrachan Correct, there are definitely items which are restricted, and you give some very good examples. When it comes to OpenShift Online, that team owns those rules.

The stuff that's public are things like the work item tracking, user profiles, etc. Essentially much of what originated from Almighty. (Essentially, project management stuff is generally public; operational stuff is generally not -- although build pipelines probably straddle that line.)

We'll figure this out on a screen-by-screen (and, in some cases, element-by-element) basis. But the original question of this issue (as I understood it) was if an anonymous user still has a navigation UI, and my basic response is 'yes'.

Helpful?

**Comment by pmuir** [comment]
@qodfathr not sure of the best mechanics for doing it, but it would be helpful to make a start on this at some point.

**Comment by qodfathr** [comment]
@pmuir I think in the existing mockups I have created, we can add a note for which ones are visible when logged-out/anonymous, and which ones are visible but behave differently when logged out/anonymous.

**Comment by pmuir** [comment]
See also #139

**Comment by joshuawilson** [comment]
This has been fixed for a while, closing.
