### ISSUE TITLE
Update Codebases

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#539]
Update Codebases to match wireframes. 

https://redhat.invisionapp.com/share/R2AWXA6DU#/screens/224263813

**Comment by dlabrecq** [comment]
I spoke with Adam about these wireframes, which are somewhat "a wish list". Thus, I implemented the codebases page based on what is currently available.

The GitHub APIs don't provide permissions, dependents, etc. I added what was available such as the last commit, license, etc.

We're not showing available branches because we cannot select one prior to launching Che. Not being able to select a branch prior to launching Che is a limitation -- it will be done via Che acording to Aslak.

Because we're not showing branches, I cannot compare them with the "commits ahead of master".

I added the workspace selection because there may be multiple workspaces to choose from. This was not part of the wireframes, but a necessary feature needed to launch Che in the proper workspace.

Creating a chart may be possible after porting the Angular Patteryfly component?

**Comment by dlabrecq** [comment]
We also cannot use the combobox shown in the wireframe.  That is a Patterfly combobox, based on jQuery. Unless we're ok with including jQuery, I have to use a dropdown or select.

**Comment by dlabrecq** [comment]
@mindreeper2420 Can you confirm that what we spoke about regarding the codebases page will be ok? Do you want to update the wireframes?

**Comment by mindreeper2420** [comment]
@dlabrecq you are correct, that items were adjusted based off of our conversation and 1-1 work. I'll update the wireframes to reflect these changes, in order to avoid further confusion.

**Comment by mindreeper2420** [comment]
@dlabrecq @joshuawilson here is the link to the updated [Codebase wireframe](https://redhat.invisionapp.com/share/FXACSF1AP#/227893822_Codebases_-_001).

@catrobson - can you replace the existing screen in the current frame to the new wireframe, based off of work with Dan?

**Comment by catrobson** [comment]
Yes, I can update.  Adam's codebases wireframes are really the rights ones to work off of anyway, but will update to keep it synced.

**Comment by dlabrecq** [comment]
I have a question about the buttons on the right of the Add Codebase panel. The Patternfly form styles currently align the button on the left -- is that acceptable? 

I've only seen buttons aligned left in the Patternfly examples. I can make it work, but would be overriding the default Patternfly styles.

**Comment by mindreeper2420** [comment]
@dlabrecq This is a known pattern discrepancy but, as the Detail Panel for Work Items has the button on the right, it should be kept on the right for the time being to keep some consistency.

**Comment by joshuawilson** [comment]
@dlabrecq we are not using jQuery, it is too large.

**Comment by catrobson** [comment]
@dlabrecq want to do a review of where you are tomorrow so we can work through any remaining questions, or are you all set?

**Comment by dlabrecq** [comment]
My questions have been answered, so I'm all set. Thanks!

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8io/fabric8-ui/pull/606

**Comment by dlabrecq** [comment]
The codebases page has gone through a couple iterations, as well as a UI redesign. I believe this can be closed now.
