### ISSUE TITLE
Update Space dashboard

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#542]
Update the Space Dashboard to match the designs.

https://redhat.invisionapp.com/share/TNAXIS9UW#/screens

Here is the same screen in the context of the Nav flow. https://redhat.invisionapp.com/share/R2AWXA6DU#/screens/224263814

**Comment by mindreeper2420** [comment]
@joshuawilson @SMahil there were a few deviations from the initial design due to the available APIs. The newsfeed was taken out, etc. @pmuir and I went through and configured it the way it is today on prod-preview.

**Comment by joshuawilson** [comment]
Based on the discussion with @catrobson, we should use a list style in the design for the home screen.

**Comment by mindreeper2420** [comment]
Ok, should be an issue drop-in. The designs can just slide into the cards without much customization.

**Comment by joshuawilson** [comment]
@dlabrecq can you take a look at the design and see if there is something that should be a component.

**Comment by catrobson** [comment]
Yes, let's see if we can follow the styling generally laid out in the user homepage widgets:  https://redhat.invisionapp.com/d/main#/console/10425298/221480597/preview

**Comment by catrobson** [comment]
Happy to talk to you while you implement about what data should go where given what we can get from the APIs - might need to deviate from the designs to build something that makes sense to the user.

**Comment by dlabrecq** [comment]
The first thing I see is the Patterfly combobox, which is based on jQuery. Unless we're ok with including jQuery, we have to use a dropdown or select. 

We have one of these in the fabric8-ui already, but it's non-functional. Someone copied the HTML output, but there is no Javascript around it to make it work.

We might create our own Angular based, combobox component. However, this won't be a straight forward port. I looked at the JavaScript earlier and punted for a Patternfly's select.

The cards could also be components. We have cards in Angular Patternfly, so that won't be difficult to port to Angular 4.

**Comment by mindreeper2420** [comment]
In order to match the designs listed by @catrobson, the cards should utilize the [Utilization Bar Card](http://www.patternfly.org/pattern-library/cards/utilization-bar-card/), with the [Card View](http://www.patternfly.org/pattern-library/content-views/card-view/#/design), [Empty State](http://www.patternfly.org/pattern-library/communication/empty-state/) and [List View](http://www.patternfly.org/pattern-library/content-views/list-view/#/design).

On the layout structure - **DO NOT** deviate from the column/grid view that PatternFly and Bootstrap utilize, or else extra (and unnecessary) code will have to be added. Everything can be dropped into the cards as is, without having to do anything other than follow the frameworks.

**Comment by joshuawilson** [comment]
No jQuery.

**Comment by pmuir** [comment]
Datawise, it's mostly correct as is. The Bayesian box needs implementing (on @arunkumars08) and the work items need ordering by created.

IMO the list style suggested by the designs is not great for comprehension, and I'm hoping that seeing the actual data in there we can improve the structure of the list views.

**Comment by joshuawilson** [comment]
@SMahil please verify and close or fix.

**Comment by joshuawilson** [comment]
This appears done. When new designs are ready we can open a new issue.
