### ISSUE TITLE
integrate Spaces/Teams in planner with Namespaces/Teams in OpenShift online

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#59]
The fabric8 Build/Run console pages are all based 100% on the kubernetes/openshift APIs. i.e. a Team is a namespace with the `fabric8-environments` `ConfigMap` inside which lists all the environments the team users etc. More [background here](http://fabric8.io/guide/terminology.html)

The upstream fabric8 console will keep this model for now; so we need a way to be able to populate the planner with teams + apps created in OpenShift Online; and vice versa so that the top right 'context switch' button & drop down is consistent between the Planner and Build/Run tabs.

e.g. if a user creates a new Team called `foo`, select it in the top right drop down, then navigate to the Build/Run it should be using the OpenShift Online `foo` namespace to view things (which would be lazily created on the fly on the users behalf).

Similar if the user switches context in the Create / Build / Run pages to the 'blah' application they create; which makes a `BuildConfig` in the `foo` namespace in OpenShift Online we need that new sub context `foo / blah` to be reflected in the top right context switcher.

We maybe need a little bridge that watches teams/apps being created in the OSO cluster (via our console or the OpenShift console or the CLI) get mirrored into the planner's idea of Teams / apps and vice versa

**Comment by jstrachan** [comment]
Here's a strawman approach for mapping external entities to the planner model:

OpenShift Namespace with Jenkins => Organisation
----------------------------------------------------------------------
a fabric8 team is an OpenShift Namespace running a Jenkins; lets map that 1-1 with some Organisation. (It could have parents and children that have no OpenShift equivalent but thats fine for now - they just map to some Organisation in some tree). Lets also make sure that the OpenShift namespace name and the labels on it are stored in the Organisation somewhere too; so that given an Organisation we can know if it maps to an OpenShift namespace or not and if so map it to the Build/Run stuff.

OpenShift BuildConfig (with git repo URL) => Space
----------------------------------------------------------------------
an OpenShift Namespace has 0…N BuildConfigs which each have a single git repo URL inside and has a name and a set of labels. Lets map each BuildConfig to a single Space in planner (and store the name, labels & git repo inside it). Again planner could add parent/child Spaces which have to OpenShift correlation; thats fine. Its OK for Spaces not to map to anything specific in OpenShift.

Labels on BuildConfig => Area
-----------------------------------------
We could - as a first cut - map each label on the BuildConfig to a child Area of the Organisation. So that if an OpenShift Organisation had 4 BuildConfigs they could use labels “tier: backend” or “tier: frontend” then we could have a backend + frontend Area so that folks in the Organisation could filter the Apps/repos by front end / back end projects (ditto for any other labels). Whats cool about this is that we can do the same filtering on the runtime Kubernetes stuff, on the Jenkins pipelines or on the planner stuff (events, issues, PRs, commits etc). There can be more Areas with no OpenShift labels association; thats fine.

Builds
--------
these are linked to a BuildConfig (so a Space) so we can associate them pretty easily. 

Deploys
-----------
these are related to a BuildConfig (so a Space) too so are easy to associate - they just also have the additional name of an environment (Test, Staging, Prod etc) too. Other than tagging Deploys and other management events with the associated ‘environment name’ I’m not sure if Planner needs to worry too much about Environments (they are more a Build/Run concept); but we could add the Environment model into planner if its helpful for visualisation; if so each Organisation can just have N environments which have a name and map to some physical openshift/kubernetes cluster and underlying namespace name.

github PR/commit/issue
--------------------------------

All github resources associate with a git repo; we could use the github HTTPS URL as the key to associate it to the Space / BuildConfig so we can associate them all to the underlying Space; so that Builds, Deploys, Commits, PRs, Issues all relate to the same logical Space to make easy queries and consolidated views etc. 



So the above is a simple one way mapping from the OpenShift/Jenkins/github resources into the planner model. Its totally fine for Planner to add lots more Organisations, Spaces or Areas (or other entities of its own choosing) at any other place in the model - as parents, children or arbitrary associations. But as long as we’ve a simple canonical mapping that handles the external OpenShift/Jenkins/github resources we can populate Planner from real projects - then it can enrich with more hierarchies, groupings, areas or whatever over time.

Or saying that another way; github and OpenShift Namespaces + BuildConfig/git repos are a pretty fixed model that should be easy to represent in a canonical way

**Comment by pmuir** [comment]
Long story short, I think spacess actually map to teams. Let me try to rewrite the above based on that.

**Comment by pmuir** [comment]
Here's Pete's strawman approach for mapping external entities to the planner model:

??? => Organisation
----------------------------------------------------------------------
TODO

OpenShift Namespace with Jenkins => Space
----------------------------------------------------------------------
a fabric8 team is an OpenShift Namespace running a Jenkins; lets map that 1-1 with some Space. Lets also make sure that the OpenShift namespace name and the labels on it are stored in the Space somewhere too; so that given an Spacewe can know if it maps to an OpenShift namespace or not and if so map it to the Build/Run stuff.

OpenShift BuildConfig (with git repo URL) => Space BuildConfig
----------------------------------------------------------------------
an OpenShift Namespace has 0…N BuildConfigs which each have a single git repo URL inside and has a name and a set of labels. Lets map each BuildConfig to a single Space BuildConfig in the platform (and store the name, labels & git repo inside it).

Labels on BuildConfig => Label on Space
-----------------------------------------
We could - as a first cut - map each label on the BuildConfig to a label on the Space. So that if an Space had 4 BuildConfigs they could use labels “tier: backend” or “tier: frontend” then we could have a backend + frontend Area so that folks in the Space could filter the Apps/repos by front end / back end projects (ditto for any other labels). Whats cool about this is that we can do the same filtering on the runtime Kubernetes stuff, on the Jenkins pipelines or on the planner stuff (events, issues, PRs, commits etc). There can be more labels with no OpenShift labels association; thats fine.

Builds
--------
these are linked to a BuildConfig (and so to a Space) so we can associate them pretty easily. 

Deploys
-----------
these are related to a BuildConfig (and so to a Space) too so are easy to associate - they just also have the additional name of an environment (Test, Staging, Prod etc) too. Other than tagging Deploys and other management events with the associated ‘environment name’ I’m not sure if work item tracker needs to worry too much about Environments (they are more a Build/Run concept); but we could add the Environment model into the work item tracker if its helpful for visualisation; if so each Space can just have N environments which have a name and map to some physical openshift/kubernetes cluster and underlying namespace name.

github PR/commit/issue
--------------------------------

All github resources associate with a git repo; we could use the github HTTPS URL as the key to associate it to the Space / BuildConfig so we can associate them all to the underlying Space; so that Builds, Deploys, Commits, PRs, Issues all relate to the same logical Space to make easy queries and consolidated views etc.

**Comment by jstrachan** [comment]
I think this issue is fixed now
