### ISSUE TITLE
User Profile: update username 'once' as part of registration 

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#804]
- The User api now returns a read-only property called "registration_completed" which is  `false` when the user first logs in. 
-  "registration_completed"=true implies that the username can be updated.
-  "registration_completed"=false implies that the username cannot be updated.
-  username can be updated only once in the registration workflow. On doing so, `registration_completed` is automatically set to `true` internally. Subsequent updates to username is not allowed.
- During (HTTP PATCH) updation , if the username already exists, then a HTTP 409 Conflict is returned. 
- "write" operation on `registration_completed`  by HTTP PATCH is not supported.

@pmuir

**Comment by dlabrecq** [comment]
I saw the newly added registration_completed attribute and we're already using it in the getting started page. However, I added the check for the 409 status.

That said, I was able to update using my existing username without any errors. I'm not able to change my username to something different now that an update has taken place. For testing purposes, it would be helpful to update the username more than once.

Fixed by:
https://github.com/fabric8io/fabric8-ui/pull/813
