### ISSUE TITLE
User Profile: Support for updating email address restored 

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#805]
Support for updating the email is restored in the API.
If the email already exists in sso for a different account, then HTTP 409 conflict is returned.
Related to : https://github.com/almighty/almighty-core/commit/b76505860a5d1dfd94e0b67eea3c9c427fd1e159

**Comment by dlabrecq** [comment]
For the update profile page, we won't allow the user to update their username. Thus, it's probably safe to assume 409 is for an invalid email.

Fixed by https://github.com/fabric8io/fabric8-ui/pull/1263

Note that there is a potential issue returning 409 for duplicate email. That is, 409 is also returned for an existing username. The /api/user API may be called to update multiple properties (e.g., on the update profile page).

If we return different status for each conflict type, the UI could better handle each use case and display an appropriate message.

**Comment by dlabrecq** [comment]
As of today, the latest profile page is available in prod.
